# Minio to GitOps Configuration
# Update these values according to your setup

minio:
  endpoint: "localhost:9000"  # Your Minio server endpoint
  access_key: "minioadmin"    # Minio access key
  secret_key: "minioadmin123" # Minio secret key
  secure: false               # Use HTTPS (true) or HTTP (false)
  bucket: "openshift-cluster-backups-4"  # Source bucket name
  prefix: "crc.testing/crc-wrl62"        # Optional: prefix path in bucket

git:
  repository: "https://github.com/walbis/test.git"  # Target Git repository
  
  # Authentication methods (choose one)
  auth_method: "ssh"  # Options: "ssh", "pat", "basic", "none"
  
  # SSH Configuration (for auth_method: "ssh")
  ssh:
    private_key_path: "~/.ssh/id_rsa"  # Path to SSH private key
    passphrase: ""                     # SSH key passphrase (if any)
  
  # Personal Access Token (for auth_method: "pat")
  # Supports GitHub, GitLab, Azure DevOps, Bitbucket
  pat:
    token: ""                          # PAT token (or use GIT_PAT_TOKEN env var)
    username: ""                       # Username for PAT (optional for some platforms)
  
  # Basic Authentication (for auth_method: "basic")
  basic:
    username: ""                       # Git username (or use GIT_USERNAME env var)
    password: ""                       # Git password (or use GIT_PASSWORD env var)
  
  # Platform-specific examples:
  # GitHub with PAT:
  #   repository: "https://github.com/username/repo.git"
  #   auth_method: "pat"
  #   pat.token: "ghp_xxxxxxxxxxxxxxxxxxxx"
  #
  # Azure DevOps with PAT:
  #   repository: "https://dev.azure.com/organization/project/_git/repository"
  #   auth_method: "pat" 
  #   pat.username: "any_string"  # Azure DevOps requires any username
  #   pat.token: "xxxxxxxxxxxxxxxxxxxx"
  #
  # GitLab with PAT:
  #   repository: "https://gitlab.com/username/repo.git"
  #   auth_method: "pat"
  #   pat.username: "oauth2"  # GitLab uses "oauth2" as username
  #   pat.token: "glpat-xxxxxxxxxxxxxxxxxxxx"
  #
  # Bitbucket with App Password:
  #   repository: "https://bitbucket.org/username/repo.git"
  #   auth_method: "basic"
  #   basic.username: "your_username"
  #   basic.password: "app_password_token"

# Cluster mappings for different environments
clusters:
  # Default mapping applied to all namespaces
  default:
    dev: "https://dev-cluster-api.example.com"
    test: "https://test-cluster-api.example.com" 
    preprod: "https://preprod-cluster-api.example.com"
    prod: "https://prod-cluster-api.example.com"
  
  # Namespace-specific overrides (optional)
  # Uncomment and modify as needed
  # berkay-test:
  #   dev: "https://special-dev-cluster.example.com"
  #   test: "https://special-test-cluster.example.com"
  #   preprod: "https://special-preprod-cluster.example.com"
  #   prod: "https://special-prod-cluster.example.com"
  #
  # cluster-backup:
  #   dev: "https://backup-dev-cluster.example.com"
  #   test: "https://backup-test-cluster.example.com"
  #   preprod: "https://backup-preprod-cluster.example.com"
  #   prod: "https://backup-prod-cluster.example.com"

# Environment-specific settings
environments:
  dev:
    sync_policy: "automated"  # automated or manual
    replicas: 1
    storage_size_small: "2Gi"
    storage_size_large: "5Gi"
    
  test:
    sync_policy: "automated"
    replicas: 1  
    storage_size_small: "1Gi"
    storage_size_large: "2Gi"
    
  preprod:
    sync_policy: "manual"
    replicas: 2
    storage_size_small: "10Gi"
    storage_size_large: "20Gi"
    
  prod:
    sync_policy: "manual"
    replicas: 3
    storage_size_small: "50Gi" 
    storage_size_large: "100Gi"